### ISSUE TITLE
Ability to turn off logs

### ISSUE THREAD

**Issue by GreenPioneer** [andjosh/mongo-throttle#6]
## Expected Behavior

The ability to silence/turn off the log
## Current Behavior

`MongoDB connection not set. Skipping Mongo-Throttle`
## Possible Solution

Send in options that allows you to select if you want to log at all

**Comment by joshbeckman** [comment]
We can just use [debug](https://www.npmjs.com/package/debug) instead of directly logging it.

**Comment by joshbeckman** [comment]
Rendered irrelevant by https://github.com/andjosh/mongo-throttle/commit/5148602b2b1b6cbbfbf9b3defd844977f6600dbe
