### ISSUE TITLE
Fix readyState

### ISSUE THREAD

**Issue by GreenPioneer** [andjosh/mongo-throttle#7]
I am using this in [MeanStackJS](https://github.com/greenpioneersolutions/meanstackjs) and it just constantly warns me about how its skipping which tells me the ready State isn't flipping to `1`. which begs the questions is it reliable or is there another way we need to be using it.

Note in the mean stack this is order of the startup below. Could it be that i have to re order to use ready state ? but then whats the point of that parameter if is not dynamic enough to updated after you connect
1. Init Mongoose
2. Configure Throttle() as middleware
3. Configure all other model
4. Connect to the db
## Expected Behavior

To not skip over the throttle or log after the mean stack sets up. 
## Current Behavior

But even after the ready state should have turned to 1 it does not even though i can see the model. At this point the rest of the system works fine except here.
## Possible Solution

None yet, need to investigate the reliability of this ready state function

**Comment by joshbeckman** [comment]
Yeah, I bet the issue is because step 4 is occurring at the last point. I'll see if there's a more reliable flag.

**Comment by joshbeckman** [comment]
I think the issue stems from:
- `mongoose` is required at the top of the file, and set into `mongoose` variable
- That variable contains a value for `readyState`
- That variable is not dynamically re-evaluated when the connection actually changes
- The middleware function checks the value of `readyState`, which is only set on `mongoose` `require`

**Comment by joshbeckman** [comment]
I don't see a better option for checking connection state, so maybe we should just drop the check altogether and assume a connection?

**Comment by GreenPioneer** [comment]
I think it was a great idea and a solid implementation figuring it was dynamic.... but since its not i think we will have to drop it and assume

**Comment by GreenPioneer** [comment]
Ill try to put something together later if you dont beat me too it. Either way lets test against the mean stack to see if we can work any way that you order your set up.
