### ISSUE TITLE
Bug: stack not connecting to mongodb

### ISSUE THREAD

**Issue by thatfatbastard** [andjosh/mongo-throttle#8]
I'm using mongo-throttle in a MEAN stack, and it seem to cause an infinite timeout when it's not commented out. I'm on version 1.0.5.

**Comment by GreenPioneer** [comment]
@andjosh  I have seen @thatfatbastard  issue and it looks like for some reason his model says the throttle is there but when he trys to run to save the IP it just gets stuck in limbo. If our Mongoose ready state was working this would have been the perfect opp.

**Comment by joshbeckman** [comment]
@thatfatbastard can you provide details about the setup flow for connections between `app`, `mongo-throttle`, and `mongoose`?

**Comment by GreenPioneer** [comment]
@andjosh Did some more looking and what it appear to be is the when we use a localhost connection for mongo everything goes smooth. No matter the order in which mongo-throttle is called. But When i use a Tri Located mongo replication across different regions i run into this issue of our packaged just hanging at the [call](https://github.com/andjosh/mongo-throttle/blob/master/lib/throttler.js#L88). If i only use one mongo in a different region it will do that same thing and basically  never allow the throttle to be in a ready state. so the throttle just hangs. 

Either way i can redo the order of the mean stack but im more interested in how can we solve the package getting hung with having to force a still or hack on users 

TESTED WITH - Devices, OS &Versions didn't make a difference
Mac Book Pro , Lenovo Thinkpad t450 (windows 7)
Node 6.9.1 & 4.8.x i forget the number
Using Mean Stack Js 1.1.0

**Comment by joshbeckman** [comment]
Well, that's tough. If we can't use Mongoose `readyState` reliably, I'm not sure how we can even be sure of a connection.
