### ISSUE TITLE
Mongoose Uri & inMemory Check

### ISSUE THREAD

**Issue by GreenPioneer** [andjosh/mongo-throttle#9]
Lets add  the mongoose connection for those who need to pass it in because of delay in the mongoose ready state. Let make sure we add back in the `readyState` to alert usering of potentially needing to add in the uri. When we use the URI we should use the `createConnection` call .

Look into the inMemory check so that if they are over the limit we store them so that we dont have to go back to the DB

**Comment by joshbeckman** [comment]
Should address #8

**Comment by GreenPioneer** [comment]
Im gonna put a commit together are you fine with adding this as the name to use

```
mongoose:{
   uri: 'mongod://blahblah'
}
```
